### ISSUE TITLE
Host rewrite

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/chrisomatic#1]
Since `chrisomatic` runs inside of the container, it connects to services via hostnames which are valid only inside the docker network. The URLs printed out are also like this. For example, after successfully registering a plugin, `chrisomatic` prints `http://chris:8000/api/v1/` instead of `http://localhost:8000/api/v1/`.

There should be a way to rewrite these outputs.

**Comment by sherrif10** [comment]
Hello @jennydaman  this looks so cool for me and am intrested in giving it a try. can you please throw more light or probably assign it to me.

**Comment by jennydaman** [comment]
I'm happy to hear that you like the project!

The proposal is to be able to configure `chrisomatic` so that the URLs it displays are changed. Maybe we can start by changing the schema of the YAML configuration file `chrisomatic.yml` to accept something like:

```yaml

on:
  cube_url: http://chris:8000/api/v1/
  cube_url_extern_host: http://localhost:8000
  chris_store_url: http://chris_store:8010/api/v1/
  chris_superuser:
    username: chris
    password: chris1234
```

To change the schema, you should first update the documentation here:

- https://github.com/FNNDSC/chrisomatic/blob/master/docs/interpretation.adoc
- https://github.com/FNNDSC/chrisomatic/blob/master/docs/schema.adoc

Next, you can change the actual code of how the YAML gets deserialized:

- https://github.com/FNNDSC/chrisomatic/blob/master/chrisomatic/spec/schema.py
- https://github.com/FNNDSC/chrisomatic/blob/fe48c55a01d3ebc985b4fa7af6d4b16d1769bd28/chrisomatic/spec/given.py#L22-L26

Finally, we'll need to figure out how to change what's displayed. This isn't exactly easy to do globally since what's displayed out to the screen are not strings but instead [rich](https://pypi.org/project/rich/) objects.
