### ISSUE TITLE
❌ superuser (chris)    Cannot create superuser without connection to Docker.  

### ISSUE THREAD

**Issue by rrbanda** [FNNDSC/chrisomatic#11]
While running `podman run --rm -i docker.io/fnndsc/chrisomatic:latest chrisomatic -t - < chrisomatic.yml` , getting the following error

<img width="924" alt="Screenshot 2023-10-26 at 8 06 12 AM" src="https://github.com/FNNDSC/chrisomatic/assets/93591339/41c19769-a1f2-4407-b42a-eb4cd78971be">

<img width="576" alt="Screenshot 2023-10-26 at 8 06 30 AM" src="https://github.com/FNNDSC/chrisomatic/assets/93591339/5651c13c-1e87-448e-81b7-41b7afb8db50">

@jennydaman please review

**Comment by veniceofcode** [comment]
The file being used for `chrisomatic.yml`


[root@chbox-edge ~]# more chrisomatic.yml 
```
# chrisomatic.yml
version: 1.2

on:
  cube_url: http://chbox-edge:8000/api/v1/
  chris_superuser:
    username: chris
    password: chris1234

cube:
  compute_resource:
    - name: host
      url: http://chbox-edge:5005/api/v1/
      innetwork: true
  plugins:
    - pl-dircopy
    - pl-tsdircopy
    - pl-topologicalcopy
```
